sudo: required
services: 
    - docker

before_install:
  - docker build -t singhlovepreet/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true singhlovepreet/react-test npm test -- --coverage

after_success:
  - docker build -t singhlovepreet/multi-client ./client
  - docker build -t singhlovepreet/multi-nginx ./nginx
  - docker build -t singhlovepreet/multi-server ./server
  - docker build -t singhlovepreet/multi-worker ./worker

  # login to docker cli
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin

  # push these images to docker hub

  - docker push singhlovepreet/multi-client
  - docker push singhlovepreet/multi-nginx
  - docker push singhlovepreet/multi-server
  - docker push singhlovepreet/multi-worker
