sudo: required
services: 
    - docker

before_install:
  - docker build -t singhlovepreet2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true singhlovepreet2/react-test npm test -- --coverage

after_success:
  - docker build -t singhlovepreet2/multi-client ./client
  - docker build -t singhlovepreet2/multi-nginx ./nginx
  - docker build -t singhlovepreet2/multi-server ./server
  - docker build -t singhlovepreet2/multi-worker ./worker

  # login to docker cli
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin

  # push these images to docker hub

  - docker push singhlovepreet2/multi-client
  - docker push singhlovepreet2/multi-nginx
  - docker push singhlovepreet2/multi-server
  - docker push singhlovepreet2/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-772022640202
  bucket_path: docker-multi

  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
