version: "3"
services:

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "4000:80"

  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: "redis"
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./server

    volumes: 
      - /app/node_modules
      - ./server:/app

    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - POSTGRES_PASSWORD=postgres_password
      - PGPORT=5432
      
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
        - /app/node_modules
        - ./client:/app
    stdin_open: true
    ports:
        - "3000:3000"

  worker:
    build:
      dockerfile: Dockerfile.dev 
      context: ./worker

    volumes: 
      - /app/node_modules
      - ./worker:/app

      